services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: bank.rabbitMq
    ports:
     - "15672:15672"
     - "5672:5672"
    restart: always
  bank.db:
    image: postgres
    container_name: bank.db
    volumes:
      - ./docker/database:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - "5433:5432"